# Generated by Django 5.0 on 2023-12-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_rating',
            new_name='rating',
        ),
    ]
