# Generated by Django 5.0 on 2024-01-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
