# Generated by Django 5.0 on 2024-03-06 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en_us',
            field=models.CharField(help_text='Имя категории', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(help_text='Имя категории', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_content_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_name_en_us',
            field=models.CharField(help_text='Имя публикации', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_name_ru',
            field=models.CharField(help_text='Имя публикации', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type_en_us',
            field=models.CharField(choices=[('NE', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type_ru',
            field=models.CharField(choices=[('NE', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(help_text='Имя категории', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='news.author', verbose_name='This is the help text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_name',
            field=models.CharField(help_text='Имя публикации', max_length=255),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='news.category', verbose_name='This is the help text'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='news.post', verbose_name='This is the help text'),
        ),
    ]
